name: Live TV
permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:      # Allows manual triggering

jobs:
  scrape-tubi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 urllib3 pysocks

      - name: Remove old files
        run: |
          rm -f livetv.m3u tv.xml
          echo "Removed old files (if they existed)"

      - name: Run tv.py
        run: python tv.py
        shell: /usr/bin/bash -e {0}
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.13.2/x64
          LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.13.2/x64/lib

      - name: Debug files and commit
        run: |
          echo "Current directory: $(/bin/pwd)"
          ls -l
          git status
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add livetv.m3u tv.xml
          echo "Files staged:"
          git status
          git commit -m "Update playlist and EPG $(date -u +'%a %b %d %T UTC %Y')"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
